---
title: "Linear Regression Model"
---

<style>
body {
text-align: justify}
</style>

```
```


### Multiple linear regression model
In this section we will introduce multiplie linear regression and its use in forecasting problems. Lets assume that company ABC produces a detergent. The company would like to develop a prediction model that can be used to predict the demand for the detergent. The demand for the detergent (in hundreds of thousands of bottles) in "sales period t", where each sales period is defined to last 4 weeks, is denoted by $y_t$ and is called the *dependent variable*. The demand for ABC's detergent is partially determined by one or more of the *independent variables*, $x_{t1}$ = the price of the detergent in period *t*, $x_{t2}$ = the average industry price in period *t* of competitors' similar detergents, and $x_{t3}$ = the advertising expenditure in period *t* of ABC to promote the detergent. The data below have been observed in the last 30 sales periods. 

```{r echo = FALSE, results = 'asis'}
library('knitr')
library('kableExtra')
deposits <- data.frame('t' = 1:30, 'Demand' = c(7.38, 8.31, 9.52, 7.50, 9.33, 8.28, 8.75, 7.87, 7.10, 8.00, 7.89, 8.15, 9.10, 8.86, 8.90, 8.87, 9.26, 9.00, 8.75, 7.95, 7.65, 7.27, 8.00, 8.50, 8.75, 9.21, 8.27, 7.67, 7.93, 9.26), 'Price' = c(3.85, 3.75, 3.70, 3.70, 3.60, 3.60, 3.60, 3.80, 3.80, 3.85, 3.90, 3.90, 3.70, 3.75, 3.75, 3.80, 3.70, 3.80, 3.70, 3.80, 3.80, 3.75, 3.70, 3.55, 3.60, 3.65, 3.70, 3.75, 3.80, 3.70), 'Average Industry Price' = c(3.80, 4.00, 4.30, 3.70, 3.85, 3.80, 3.75, 3.85, 3.65, 4.00, 4.10, 4.00, 4.10, 4.20, 4.10, 4.10, 4.20, 4.30, 4.10, 3.75, 3.75, 3.65, 3.90, 3.65, 4.10, 4.25, 3.65, 3.75, 3.85, 4.25), 'Advertising Expenditure' = c(5.50, 6.75, 7.25, 5.50, 7.00, 6.50, 6.75, 5.25, 5.25, 6.00, 6.50, 6.25, 7.00, 6.90, 6.80, 6.80, 7.10, 7.00, 6.80, 6.50, 6.25, 6.00, 6.50, 7.00, 6.80, 6.80, 6.50, 5.75, 5.80, 6.80))

knitr::kable(deposits, caption = 'Historical data relevant to the demand for ABC detergent') %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
# knitr::kable(deposits, caption = 'Time Series Data: Quarterly Values of Time-Deposits') 
```



```
```

